
// This file has been generated by the GUI designer. Do not modify.
namespace Nuevo
{
	public partial class Window
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Action EscenarioAction;
		
		private global::Gtk.Action NuevoEscenarioAction;
		
		private global::Gtk.Action SimulacinAction;
		
		private global::Gtk.Action NuevaSimulacinAction;
		
		private global::Gtk.Action ConfiguracinAction;
		
		private global::Gtk.Action PropiedadesAction;
		
		private global::Gtk.Action ParmetrosAction;
		
		private global::Gtk.Action mediaPauseAction;
		
		private global::Gtk.Action mediaPlayAction;
		
		private global::Gtk.Action zoomInButton;
		
		private global::Gtk.Action zoomOutButton;
		
		private global::Gtk.Action undoAction;
		
		private global::Gtk.ToggleAction contornoButton;
		
		private global::Gtk.RadioAction circuloButton;
		
		private global::Gtk.RadioAction rectanguloButton;
		
		private global::Gtk.RadioAction lineaButton;
		
		private global::Gtk.Action GuardarEscenarioAction;
		
		private global::Gtk.Action CargarEscenarioAction;
		
		private global::Gtk.Action EscenarioEnBlancoAction;
		
		private global::Gtk.Action EscenarioDesdeArchivoAction;
		
		private global::Gtk.ToggleAction calorButton;
		
		private global::Gtk.Action EstadsticaAction;
		
		private global::Gtk.Action MtricasAction;
		
		private global::Gtk.ToggleAction grillaButton;
		
		private global::Gtk.RadioAction puntoInicioAction;
		
		private global::Gtk.RadioAction puntoObjetivoAction;
		
		private global::Gtk.Action Action;
		
		private global::Gtk.ToggleAction trayectoriasAction;
		
		private global::Gtk.Action GrficaAction;
		
		private global::Gtk.Action IniciarOgre3DAction;
		
		private global::Gtk.Action ExportarAVTKAction;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.MenuBar menubar1;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Toolbar toolbar1;
		
		private global::Gtk.Toolbar toolbar2;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label labelNivel;
		
		private global::Gtk.SpinButton spinbuttonNivel;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Label labelIntermitencia;
		
		private global::Gtk.SpinButton spinbuttonIntermitencia;
		
		private global::Gtk.ScrolledWindow scrolledwindow1;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Label labelRender;
		
		private global::Gtk.Label labelAlgorithm;
		
		private global::Gtk.Label labelIteraciones;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Nuevo.Window
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.EscenarioAction = new global::Gtk.Action ("EscenarioAction", global::Mono.Unix.Catalog.GetString ("Escenario"), null, null);
			this.EscenarioAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Escenario");
			w1.Add (this.EscenarioAction, null);
			this.NuevoEscenarioAction = new global::Gtk.Action ("NuevoEscenarioAction", global::Mono.Unix.Catalog.GetString ("Nuevo escenario"), null, null);
			this.NuevoEscenarioAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Nuevo escenario");
			w1.Add (this.NuevoEscenarioAction, null);
			this.SimulacinAction = new global::Gtk.Action ("SimulacinAction", global::Mono.Unix.Catalog.GetString ("Simulación"), null, null);
			this.SimulacinAction.Sensitive = false;
			this.SimulacinAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Simulación");
			w1.Add (this.SimulacinAction, null);
			this.NuevaSimulacinAction = new global::Gtk.Action ("NuevaSimulacinAction", global::Mono.Unix.Catalog.GetString ("Nueva simulación"), null, null);
			this.NuevaSimulacinAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Nueva simulación");
			w1.Add (this.NuevaSimulacinAction, null);
			this.ConfiguracinAction = new global::Gtk.Action ("ConfiguracinAction", global::Mono.Unix.Catalog.GetString ("Configuración"), null, null);
			this.ConfiguracinAction.Sensitive = false;
			this.ConfiguracinAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Configuración");
			w1.Add (this.ConfiguracinAction, null);
			this.PropiedadesAction = new global::Gtk.Action ("PropiedadesAction", global::Mono.Unix.Catalog.GetString ("Propiedades"), null, null);
			this.PropiedadesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Propiedades");
			w1.Add (this.PropiedadesAction, null);
			this.ParmetrosAction = new global::Gtk.Action ("ParmetrosAction", global::Mono.Unix.Catalog.GetString ("Parámetros"), null, null);
			this.ParmetrosAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Parámetros");
			w1.Add (this.ParmetrosAction, null);
			this.mediaPauseAction = new global::Gtk.Action ("mediaPauseAction", global::Mono.Unix.Catalog.GetString ("Pausa"), null, "gtk-media-pause");
			this.mediaPauseAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Pausa");
			w1.Add (this.mediaPauseAction, null);
			this.mediaPlayAction = new global::Gtk.Action ("mediaPlayAction", global::Mono.Unix.Catalog.GetString ("Play"), null, "gtk-media-play");
			this.mediaPlayAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Play");
			w1.Add (this.mediaPlayAction, null);
			this.zoomInButton = new global::Gtk.Action ("zoomInButton", null, null, "gtk-zoom-in");
			w1.Add (this.zoomInButton, null);
			this.zoomOutButton = new global::Gtk.Action ("zoomOutButton", null, null, "gtk-zoom-out");
			w1.Add (this.zoomOutButton, null);
			this.undoAction = new global::Gtk.Action ("undoAction", global::Mono.Unix.Catalog.GetString ("Restaurar parámetros"), null, "gtk-undo");
			this.undoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Restaurar parámetros");
			w1.Add (this.undoAction, null);
			this.contornoButton = new global::Gtk.ToggleAction ("contornoButton", global::Mono.Unix.Catalog.GetString ("Contorno boids"), null, "gtk-no");
			this.contornoButton.ShortLabel = global::Mono.Unix.Catalog.GetString ("Contorno boids");
			w1.Add (this.contornoButton, null);
			this.circuloButton = new global::Gtk.RadioAction ("circuloButton", global::Mono.Unix.Catalog.GetString ("Circulo"), null, "gtk-cdrom", 0);
			this.circuloButton.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.circuloButton.ShortLabel = global::Mono.Unix.Catalog.GetString ("Circulo");
			w1.Add (this.circuloButton, null);
			this.rectanguloButton = new global::Gtk.RadioAction ("rectanguloButton", global::Mono.Unix.Catalog.GetString ("Rectángulo"), null, "gtk-indent", 0);
			this.rectanguloButton.Group = this.circuloButton.Group;
			this.rectanguloButton.ShortLabel = global::Mono.Unix.Catalog.GetString ("Rectángulo");
			w1.Add (this.rectanguloButton, null);
			this.lineaButton = new global::Gtk.RadioAction ("lineaButton", global::Mono.Unix.Catalog.GetString ("Línea"), null, "gtk-color-picker", 0);
			this.lineaButton.Group = this.circuloButton.Group;
			this.lineaButton.ShortLabel = global::Mono.Unix.Catalog.GetString ("Línea");
			w1.Add (this.lineaButton, null);
			this.GuardarEscenarioAction = new global::Gtk.Action ("GuardarEscenarioAction", global::Mono.Unix.Catalog.GetString ("Guardar escenario"), null, null);
			this.GuardarEscenarioAction.Sensitive = false;
			this.GuardarEscenarioAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Guardar escenario");
			w1.Add (this.GuardarEscenarioAction, null);
			this.CargarEscenarioAction = new global::Gtk.Action ("CargarEscenarioAction", global::Mono.Unix.Catalog.GetString ("Cargar escenario"), null, null);
			this.CargarEscenarioAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Cargar escenario");
			w1.Add (this.CargarEscenarioAction, null);
			this.EscenarioEnBlancoAction = new global::Gtk.Action ("EscenarioEnBlancoAction", global::Mono.Unix.Catalog.GetString ("Escenario en blanco"), null, null);
			this.EscenarioEnBlancoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Escenario en blanco");
			w1.Add (this.EscenarioEnBlancoAction, null);
			this.EscenarioDesdeArchivoAction = new global::Gtk.Action ("EscenarioDesdeArchivoAction", global::Mono.Unix.Catalog.GetString ("Escenario desde archivo"), null, null);
			this.EscenarioDesdeArchivoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Escenario desde archivo");
			w1.Add (this.EscenarioDesdeArchivoAction, null);
			this.calorButton = new global::Gtk.ToggleAction ("calorButton", global::Mono.Unix.Catalog.GetString ("Mapa de calor"), null, "gtk-select-color");
			this.calorButton.ShortLabel = global::Mono.Unix.Catalog.GetString ("Mapa de calor");
			w1.Add (this.calorButton, null);
			this.EstadsticaAction = new global::Gtk.Action ("EstadsticaAction", global::Mono.Unix.Catalog.GetString ("Estadística"), null, null);
			this.EstadsticaAction.Sensitive = false;
			this.EstadsticaAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Estadistica");
			w1.Add (this.EstadsticaAction, null);
			this.MtricasAction = new global::Gtk.Action ("MtricasAction", global::Mono.Unix.Catalog.GetString ("Métricas"), null, null);
			this.MtricasAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Métricas");
			w1.Add (this.MtricasAction, null);
			this.grillaButton = new global::Gtk.ToggleAction ("grillaButton", global::Mono.Unix.Catalog.GetString ("Grillado"), null, "gtk-leave-fullscreen");
			this.grillaButton.ShortLabel = global::Mono.Unix.Catalog.GetString ("Grillado");
			w1.Add (this.grillaButton, null);
			this.puntoInicioAction = new global::Gtk.RadioAction ("puntoInicioAction", global::Mono.Unix.Catalog.GetString ("Punto de inicio"), null, "gtk-home", 0);
			this.puntoInicioAction.Group = this.circuloButton.Group;
			this.puntoInicioAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Punto de inicio");
			w1.Add (this.puntoInicioAction, null);
			this.puntoObjetivoAction = new global::Gtk.RadioAction ("puntoObjetivoAction", global::Mono.Unix.Catalog.GetString ("Punto objetivo"), null, "gtk-jump-to", 0);
			this.puntoObjetivoAction.Group = this.circuloButton.Group;
			this.puntoObjetivoAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Punto objetivo");
			w1.Add (this.puntoObjetivoAction, null);
			this.Action = new global::Gtk.Action ("Action", null, null, null);
			w1.Add (this.Action, null);
			this.trayectoriasAction = new global::Gtk.ToggleAction ("trayectoriasAction", global::Mono.Unix.Catalog.GetString ("Trayectorias"), null, "gtk-redo");
			this.trayectoriasAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Trayectorias");
			w1.Add (this.trayectoriasAction, null);
			this.GrficaAction = new global::Gtk.Action ("GrficaAction", global::Mono.Unix.Catalog.GetString ("Gráfica"), null, null);
			this.GrficaAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Gráfica");
			w1.Add (this.GrficaAction, null);
			this.IniciarOgre3DAction = new global::Gtk.Action ("IniciarOgre3DAction", global::Mono.Unix.Catalog.GetString ("Iniciar Ogre3D"), null, null);
			this.IniciarOgre3DAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Iniciar Ogre3D");
			w1.Add (this.IniciarOgre3DAction, null);
			this.ExportarAVTKAction = new global::Gtk.Action ("ExportarAVTKAction", global::Mono.Unix.Catalog.GetString ("Exportar a VTK"), null, null);
			this.ExportarAVTKAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Exportar a VTK");
			w1.Add (this.ExportarAVTKAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "Nuevo.Window";
			this.Title = global::Mono.Unix.Catalog.GetString ("Window");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Nuevo.Window.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString (@"<ui><menubar name='menubar1'><menu name='EscenarioAction' action='EscenarioAction'><menuitem name='NuevoEscenarioAction' action='NuevoEscenarioAction'/><menu name='CargarEscenarioAction' action='CargarEscenarioAction'><menuitem name='EscenarioEnBlancoAction' action='EscenarioEnBlancoAction'/><menuitem name='EscenarioDesdeArchivoAction' action='EscenarioDesdeArchivoAction'/></menu><separator/><menuitem name='GuardarEscenarioAction' action='GuardarEscenarioAction'/></menu><menu name='SimulacinAction' action='SimulacinAction'><menuitem name='NuevaSimulacinAction' action='NuevaSimulacinAction'/></menu><menu name='ConfiguracinAction' action='ConfiguracinAction'><menuitem name='PropiedadesAction' action='PropiedadesAction'/><menuitem name='ParmetrosAction' action='ParmetrosAction'/><menuitem name='IniciarOgre3DAction' action='IniciarOgre3DAction'/></menu><menu name='EstadsticaAction' action='EstadsticaAction'><menuitem name='MtricasAction' action='MtricasAction'/><menuitem name='GrficaAction' action='GrficaAction'/><menuitem name='ExportarAVTKAction' action='ExportarAVTKAction'/></menu></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox2.Add (this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString (@"<ui><toolbar name='toolbar1'><toolitem name='mediaPauseAction' action='mediaPauseAction'/><toolitem name='mediaPlayAction' action='mediaPlayAction'/><separator/><toolitem name='zoomInButton' action='zoomInButton'/><toolitem name='zoomOutButton' action='zoomOutButton'/><separator/><toolitem name='undoAction' action='undoAction'/><separator/><toolitem name='contornoButton' action='contornoButton'/><toolitem name='grillaButton' action='grillaButton'/><separator/><toolitem name='calorButton' action='calorButton'/><toolitem name='trayectoriasAction' action='trayectoriasAction'/></toolbar></ui>");
			this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
			this.toolbar1.Sensitive = false;
			this.toolbar1.Name = "toolbar1";
			this.toolbar1.ShowArrow = false;
			this.toolbar1.ToolbarStyle = ((global::Gtk.ToolbarStyle)(2));
			this.toolbar1.IconSize = ((global::Gtk.IconSize)(2));
			this.hbox1.Add (this.toolbar1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.toolbar1]));
			w3.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString (@"<ui><toolbar name='toolbar2'><toolitem name='circuloButton' action='circuloButton'/><toolitem name='rectanguloButton' action='rectanguloButton'/><toolitem name='lineaButton' action='lineaButton'/><separator/><toolitem name='puntoInicioAction' action='puntoInicioAction'/><toolitem name='puntoObjetivoAction' action='puntoObjetivoAction'/></toolbar></ui>");
			this.toolbar2 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar2")));
			this.toolbar2.Sensitive = false;
			this.toolbar2.Name = "toolbar2";
			this.toolbar2.ShowArrow = false;
			this.toolbar2.ToolbarStyle = ((global::Gtk.ToolbarStyle)(2));
			this.toolbar2.IconSize = ((global::Gtk.IconSize)(2));
			this.hbox1.Add (this.toolbar2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.toolbar2]));
			w4.Position = 1;
			w4.Expand = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Homogeneous = true;
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.labelNivel = new global::Gtk.Label ();
			this.labelNivel.Sensitive = false;
			this.labelNivel.Name = "labelNivel";
			this.labelNivel.LabelProp = global::Mono.Unix.Catalog.GetString ("Nivel del objetivo");
			this.hbox2.Add (this.labelNivel);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.labelNivel]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.spinbuttonNivel = new global::Gtk.SpinButton (1D, 1D, 1D);
			this.spinbuttonNivel.Sensitive = false;
			this.spinbuttonNivel.CanFocus = true;
			this.spinbuttonNivel.Name = "spinbuttonNivel";
			this.spinbuttonNivel.Adjustment.PageIncrement = 10D;
			this.spinbuttonNivel.ClimbRate = 1D;
			this.spinbuttonNivel.Numeric = true;
			this.spinbuttonNivel.Value = 1D;
			this.hbox2.Add (this.spinbuttonNivel);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.spinbuttonNivel]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox3.Add (this.hbox2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox2]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Homogeneous = true;
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.labelIntermitencia = new global::Gtk.Label ();
			this.labelIntermitencia.Sensitive = false;
			this.labelIntermitencia.Name = "labelIntermitencia";
			this.labelIntermitencia.LabelProp = global::Mono.Unix.Catalog.GetString ("Intermitencia");
			this.hbox3.Add (this.labelIntermitencia);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.labelIntermitencia]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.spinbuttonIntermitencia = new global::Gtk.SpinButton (0D, 500D, 1D);
			this.spinbuttonIntermitencia.Sensitive = false;
			this.spinbuttonIntermitencia.CanFocus = true;
			this.spinbuttonIntermitencia.Name = "spinbuttonIntermitencia";
			this.spinbuttonIntermitencia.Adjustment.PageIncrement = 10D;
			this.spinbuttonIntermitencia.ClimbRate = 1D;
			this.spinbuttonIntermitencia.Numeric = true;
			this.hbox3.Add (this.spinbuttonIntermitencia);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.spinbuttonIntermitencia]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.vbox3.Add (this.hbox3);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox3]));
			w10.Position = 1;
			w10.Expand = false;
			w10.Fill = false;
			this.hbox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			this.vbox2.Add (this.scrolledwindow1);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.scrolledwindow1]));
			w13.Position = 2;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.labelRender = new global::Gtk.Label ();
			this.labelRender.Name = "labelRender";
			this.hbox4.Add (this.labelRender);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.labelRender]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.labelAlgorithm = new global::Gtk.Label ();
			this.labelAlgorithm.Name = "labelAlgorithm";
			this.hbox4.Add (this.labelAlgorithm);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.labelAlgorithm]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.labelIteraciones = new global::Gtk.Label ();
			this.labelIteraciones.Name = "labelIteraciones";
			this.labelIteraciones.Xalign = 0F;
			this.hbox4.Add (this.labelIteraciones);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.labelIteraciones]));
			w16.Position = 2;
			w16.Expand = false;
			w16.Fill = false;
			this.vbox2.Add (this.hbox4);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox4]));
			w17.Position = 3;
			w17.Expand = false;
			w17.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 1475;
			this.DefaultHeight = 300;
			this.Show ();
			this.NuevoEscenarioAction.Activated += new global::System.EventHandler (this.OnNuevoEscenarioActionActivated);
			this.NuevaSimulacinAction.Activated += new global::System.EventHandler (this.OnNuevaSimulacinActionActivated);
			this.PropiedadesAction.Activated += new global::System.EventHandler (this.OnPropiedadesActionActivated);
			this.ParmetrosAction.Activated += new global::System.EventHandler (this.OnParmetrosActionActivated);
			this.mediaPauseAction.Activated += new global::System.EventHandler (this.OnPausaButtonActivated);
			this.mediaPlayAction.Activated += new global::System.EventHandler (this.OnPlayButtonActivated);
			this.zoomInButton.Activated += new global::System.EventHandler (this.OnZoomInButtonActivated);
			this.zoomOutButton.Activated += new global::System.EventHandler (this.OnZoomOutButtonActivated);
			this.undoAction.Activated += new global::System.EventHandler (this.OnResetButtonActivated);
			this.GuardarEscenarioAction.Activated += new global::System.EventHandler (this.OnGuardarEscenarioActionActivated);
			this.EscenarioEnBlancoAction.Activated += new global::System.EventHandler (this.OnEscenarioEnBlancoActionActivated);
			this.EscenarioDesdeArchivoAction.Activated += new global::System.EventHandler (this.OnEscenarioDesdeArchivoActionActivated);
			this.MtricasAction.Activated += new global::System.EventHandler (this.OnMtricasActionActivated);
			this.GrficaAction.Activated += new global::System.EventHandler (this.OnGrficaActionActivated);
			this.IniciarOgre3DAction.Activated += new global::System.EventHandler (this.OnIniciarOgre3DActionActivated);
			this.ExportarAVTKAction.Activated += new global::System.EventHandler (this.OnExportarAVTKActionActivated);
		}
	}
}
