
// This file has been generated by the GUI designer. Do not modify.
namespace Nuevo
{
	public partial class DialogoMetricas
	{
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Label label4;
		
		private global::Gtk.Label label5;
		
		private global::Gtk.VBox vbox3;
		
		private global::Gtk.Label min_tiempo;
		
		private global::Gtk.Label max_tiempo;
		
		private global::Gtk.Label tiempo_prom;
		
		private global::Gtk.Label max_vecinos;
		
		private global::Gtk.Label min_vecinos;
		
		private global::Gtk.Label labelMiliseg;
		
		private global::Gtk.Button button794;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Nuevo.DialogoMetricas
			this.WidthRequest = 500;
			this.HeightRequest = 300;
			this.Name = "Nuevo.DialogoMetricas";
			this.Title = global::Mono.Unix.Catalog.GetString ("Métricas");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Resizable = false;
			this.Gravity = ((global::Gdk.Gravity)(10));
			// Internal child Nuevo.DialogoMetricas.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Homogeneous = true;
			this.vbox2.Spacing = 16;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.Xalign = 0F;
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Tiempo mínimo en alcanzar objetivo");
			this.vbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Tiempo máximo en alcanzar objetivo");
			this.vbox2.Add (this.label2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label2]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Tiempo promedio en alcanzar objetivo");
			this.vbox2.Add (this.label3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label3]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Máxima cantidad de vecinos de un boid");
			this.vbox2.Add (this.label4);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label4]));
			w5.Position = 3;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.Xalign = 0F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Mínima cantidad de vecinos de un boid");
			this.vbox2.Add (this.label5);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label5]));
			w6.Position = 4;
			w6.Expand = false;
			w6.Fill = false;
			this.hbox6.Add (this.vbox2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.vbox2]));
			w7.Position = 0;
			w7.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Homogeneous = true;
			this.vbox3.Spacing = 16;
			// Container child vbox3.Gtk.Box+BoxChild
			this.min_tiempo = new global::Gtk.Label ();
			this.min_tiempo.Name = "min_tiempo";
			this.min_tiempo.Xalign = 0F;
			this.min_tiempo.LabelProp = global::Mono.Unix.Catalog.GetString ("label6");
			this.vbox3.Add (this.min_tiempo);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.min_tiempo]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.max_tiempo = new global::Gtk.Label ();
			this.max_tiempo.Name = "max_tiempo";
			this.max_tiempo.Xalign = 0F;
			this.max_tiempo.LabelProp = global::Mono.Unix.Catalog.GetString ("label7");
			this.vbox3.Add (this.max_tiempo);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.max_tiempo]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.tiempo_prom = new global::Gtk.Label ();
			this.tiempo_prom.Name = "tiempo_prom";
			this.tiempo_prom.Xalign = 0F;
			this.tiempo_prom.LabelProp = global::Mono.Unix.Catalog.GetString ("label8");
			this.vbox3.Add (this.tiempo_prom);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.tiempo_prom]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.max_vecinos = new global::Gtk.Label ();
			this.max_vecinos.Name = "max_vecinos";
			this.max_vecinos.Xalign = 0F;
			this.max_vecinos.LabelProp = global::Mono.Unix.Catalog.GetString ("label9");
			this.vbox3.Add (this.max_vecinos);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.max_vecinos]));
			w11.Position = 3;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.min_vecinos = new global::Gtk.Label ();
			this.min_vecinos.Name = "min_vecinos";
			this.min_vecinos.Xalign = 0F;
			this.min_vecinos.LabelProp = global::Mono.Unix.Catalog.GetString ("label10");
			this.vbox3.Add (this.min_vecinos);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.min_vecinos]));
			w12.Position = 4;
			w12.Expand = false;
			w12.Fill = false;
			this.hbox6.Add (this.vbox3);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.vbox3]));
			w13.Position = 1;
			w13.Fill = false;
			w1.Add (this.hbox6);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(w1 [this.hbox6]));
			w14.Position = 0;
			w14.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.labelMiliseg = new global::Gtk.Label ();
			this.labelMiliseg.Name = "labelMiliseg";
			this.labelMiliseg.LabelProp = global::Mono.Unix.Catalog.GetString ("Labelmilisec");
			w1.Add (this.labelMiliseg);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(w1 [this.labelMiliseg]));
			w15.Position = 1;
			w15.Fill = false;
			// Internal child Nuevo.DialogoMetricas.ActionArea
			global::Gtk.HButtonBox w16 = this.ActionArea;
			w16.Name = "dialog1_ActionArea";
			w16.Spacing = 10;
			w16.BorderWidth = ((uint)(5));
			w16.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.button794 = new global::Gtk.Button ();
			this.button794.CanFocus = true;
			this.button794.Name = "button794";
			this.button794.UseUnderline = true;
			this.button794.Label = global::Mono.Unix.Catalog.GetString ("Aceptar");
			this.AddActionWidget (this.button794, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w17 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w16 [this.button794]));
			w17.Expand = false;
			w17.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 500;
			this.DefaultHeight = 300;
			this.Show ();
			this.button794.Pressed += new global::System.EventHandler (this.OnButton794Pressed);
		}
	}
}
